[package]
name = "sfp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
env_logger = "0.10.0"
log = "0.4.20"
termcolor = "1.3.0"
